-- phpMyAdmin SQL Dump
-- version 4.4.10
-- http://www.phpmyadmin.net
--
-- Client :  localhost:3306
-- Généré le :  Lun 30 Mai 2016 à 14:15
-- Version du serveur :  5.5.42
-- Version de PHP :  5.6.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Base de données :  `javascriptlabo`
--

-- --------------------------------------------------------

--
-- Structure de la table `events`
--

CREATE TABLE `events` (
  `id` int(255) NOT NULL,
  `titre` varchar(255) COLLATE utf8_bin NOT NULL,
  `description` text COLLATE utf8_bin NOT NULL,
  `couleur` varchar(255) COLLATE utf8_bin NOT NULL,
  `date` date NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=62 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--
-- Contenu de la table `events`
--

INSERT INTO `events` (`id`, `titre`, `description`, `couleur`, `date`) VALUES
(21, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'success', '2016-05-08'),
(24, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'info', '2016-05-01'),
(25, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'success', '2016-05-25'),
(26, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'warning', '2016-05-06'),
(27, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'success', '2016-05-31'),
(28, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'danger', '2016-05-26'),
(30, 'Test', 'gsetdfdfssfdfsdfs', 'primary', '2016-05-18'),
(31, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'success', '2016-05-17'),
(32, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'success', '2016-05-17'),
(33, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'infos', '2016-05-03'),
(34, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'success', '2016-05-05'),
(36, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'success', '2016-05-06'),
(37, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'warning', '2016-05-27'),
(38, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'success', '2016-05-23'),
(39, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'primary', '2016-05-23'),
(40, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'success', '2016-05-17'),
(41, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'primary', '2016-05-17'),
(42, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'info', '2016-05-06'),
(43, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'success', '2016-05-17'),
(44, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'danger', '2016-05-09'),
(45, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'success', '2016-05-21'),
(46, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'warning', '2016-05-12'),
(47, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'success', '2016-05-07'),
(48, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'success', '2016-05-31'),
(49, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'danger', '2016-05-11'),
(50, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'success', '2016-05-19'),
(51, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'danger', '2016-05-18'),
(52, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'success', '2016-05-04'),
(53, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'primary', '2016-05-25'),
(54, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'success', '2016-05-12'),
(55, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'info', '2016-05-13'),
(56, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'success', '2016-05-13'),
(58, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'success', '2016-06-08'),
(59, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'success', '2016-05-31'),
(60, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'success', '2016-06-25'),
(61, 'Mon anniversaire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget sapien tincidunt, blandit dolor ut, dapibus sapien. Quisque viverra cursus arcu, id molestie quam aliquet ut. Suspendisse hendrerit mattis eros in gravida. In hac habitasse platea dictumst. Praesent posuere ex id feugiat molestie. Cras condimentum molestie posuere. Etiam dapibus lobortis nunc, at maximus mi gravida nec. Etiam id enim rhoncus sem eleifend tristique et ut est. Mauris lectus diam, rhoncus nec venenatis eget, rhoncus vitae est. Nullam bibendum, nulla et porttitor dictum, metus dui convallis dolor, fermentum faucibus dolor tortor volutpat orci. Morbi lobortis elit id risus dapibus, non lacinia elit viverra. Morbi venenatis sapien tortor.', 'success', '2016-05-08');

--
-- Index pour les tables exportées
--

--
-- Index pour la table `events`
--
ALTER TABLE `events`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables exportées
--

--
-- AUTO_INCREMENT pour la table `events`
--
ALTER TABLE `events`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=62;